### ISSUE TITLE
Unable to import BatchNorm from tinygrad.nn

### ISSUE THREAD

**Issue by ethanbleier** [geohot/ai-notebooks#12]
trouble importing and using the BatchNorm class from tinygrad.nn

### my env
- 3.12
- tinygrad installation path: `/Users/name/miniconda/lib/python3.12/site-packages`

### reproducible
1. Attempt to import BatchNorm:
   ```python
   from tinygrad.nn import BatchNorm
   ```

`nn.BatchNorm(32, affine=False, track_running_stats=False),`

AttributeError: module 'tinygrad.nn' has no attribute 'BatchNorm'

### attempts
1. Uninstalled and reinstalled tinygrad with pip
2. Checked the contents of tinygrad.nn using `dir(tinygrad.nn)`, BatchNorm was not listed.
5. tried adding to PYTHONPATH, no avail

### some context
- My tinygrad installation is in a Miniconda environment
- All other components working nicely

Has BatchNorm usage changed lately?

**Comment by mintisan** [comment]
how do you solved? I encountered the same issue on macOS or Windows
